import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../assets/styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kegthat Brewing Calculators</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Kegthat.com Calculators!</h1>

        <p className={styles.description}>
          Get started by selecting one of the calculators below!{" "}
        </p>

        <div className={styles.grid}>
          <Link href="/abv">
            <div className={styles.card}>
              <h2>Abv Calculator &rarr;</h2>
              <p>
                Calculate the Alcohol by Volume using original and final
                gravity.
              </p>
            </div>
          </Link>

          <Link href="/ibu">
            <div className={styles.card}>
              <h2>IBU Calculator &rarr;</h2>
              <p>
                International bittering units are used to tell how bitter your
                beer is.
              </p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  );
};

export default Home;
